
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[540] =
    {   0,
        0,    0,   94,   92,   88,   89,   92,   92,   91,   69,
       63,   64,   79,   77,   67,   78,   68,   80,   83,   76,
       70,   75,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   65,   66,   88,   72,    0,   84,    0,   91,
       90,    0,   83,   74,   71,   73,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   86,   61,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   39,   87,
       87,   87,   87,   87,   90,   82,   60,   87,   87,   87,

       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,    0,   87,    0,    0,   87,   81,
       62,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   87,   85,   87,   87,   87,
       87,   48,   87,   87,   87,   36,   87,   87,    0,   87,
       19,   87,    0,   38,   87,    0,   87,    0,    0,   11,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   87,
       20,    0,   87,    0,   24,   49,   87,   87,   87,   87,
       87,   87,   22,   87,   87,    0,   87,    0,    0,   87,
        0,   87,    0,    0,   87,   18,   23,   14,   87,   50,

        0,   87,   87,    0,    0,    0,    0,   87,    0,    0,
       87,    0,   87,   87,    0,   87,   87,   87,    0,    0,
        0,    0,   10,    0,   87,    0,    0,   87,   87,    0,
       87,   43,   21,    0,    0,    0,    0,   45,    0,    0,
        0,    0,   59,   87,    0,   87,   87,    0,    0,    0,
        0,    0,    2,   87,    0,    0,   87,   87,    0,   87,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        9,   87,    0,   17,   87,    0,    0,    4,    0,    0,
       37,    1,   87,   16,   44,   87,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   87,

        0,   87,    0,    0,    3,    0,    0,   87,   26,    0,
       41,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    5,   42,    0,
        7,    0,    0,    0,    0,    0,    0,    0,   13,    0,
        0,    0,    0,    0,   12,   25,    0,    8,    0,    0,
        0,    6,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   35,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   40,    0,    0,   15,   33,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   32,    0,    0,    0,    0,    0,    0,
        0,    0,   47,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   46,   51,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   31,    0,    0,   34,    0,    0,    0,   52,    0,
        0,   56,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,   57,    0,    0,    0,
        0,   29,    0,    0,    0,    0,   55,    0,    0,    0,
        0,   58,    0,    0,    0,    0,   53,   54,   27,    0,
        0,    0,    0,    0,   30,    0,    0,   28,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    1,    1,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,    1,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   30,
        1,   46,    1,    1,   30,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   30,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   30,   71,    1,   72,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    1,    1,    1,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1
    } ;

static const flex_int16_t yy_base[544] =
    {   0,
        0,    0, 1004, 1005,   71, 1005,  984,   68,    0, 1005,
     1005, 1005, 1005, 1005, 1005, 1005, 1005,  986,   61,  982,
      981,  980,   43,   54,   59,   60,   50,   75,   61,    0,
       59,   52,   55,   60,   87,   62,  107,  103,  111,  105,
      127,   78, 1005, 1005,   84, 1005,  127, 1005,  995,    0,
        0,  980,  125, 1005, 1005, 1005,    0,  113,  137,  112,
      128,  138,  100,  138,  143,  155,  158,  117,  147,  153,
      160,  992,  168,  991,  990,  155,  168,  155,    0,  168,
      159,  159,  179,  180,  176,  190,  163,  183,    0,  182,
      177,  187,  188,  190,    0,  976,    0,  209,  212,  192,

      213,  207,  202,  209,  205,  209,  223,  988,  213,  225,
      228,  987,  222,  223,  226,  223,  221,  224,  226,    0,
        0,  246,  233,  248,  255,  256,  246,  249,  252,  251,
      253,  986,  259,  985,  261,  268,    0,  266,  266,  276,
      263,    0,  270,  281,  268,    0,  286,  290,  284,  276,
        0,  984,  289,    0,  298,  297,  305,  303,  313,    0,
      298,  299,  307,  304,  306,  320,  983,  307,  307,  982,
        0,  334,  329,  336,    0,    0,  328,  981,  329,  330,
      980,  335,    0,  344,  330,  337,  979,  334,  357,  358,
      342,  365,  350,  358,  350,    0,    0,    0,  355,    0,

      360,  372,  362,  372,  380,  377,  368,  391,  372,  381,
      978,  399,  388,  404,  402,  396,  394,  977,  392,  404,
      409,  415,    0,  414,  404,  419,  419,  416,  423,  415,
      428,    0,    0,  421,  434,  439,  436,    0,  437,  443,
      457,  429,    0,  432,  439,  437,  452,  453,  454,  459,
      460,  468,  965,  474,  458,  463,  465,  975,  468,  974,
      477,  477,  479,  480,  479,  498,  484,  485,  499,  493,
     1005,  505,  504,    0,  509,  499,  507,  962,  494,  972,
     1005, 1005,  516, 1005, 1005,  516,  504,  507,  506,  519,
      511,  520,  971,  515,  518,  520,  517,  524,  525,  970,

      549,  969,  550,  535, 1005,  968,  547,  967,  966,  550,
     1005,  552,  549,  551,  557,  553,  566,  567,  572,  573,
      560,  964,  570,  573,  580,  572,  582,  580,  582,  578,
      593,  587,  597,  585,  584,  591,  601,  596,  599,  611,
      607,  600,  961,  611,  609,  619,  601,  954,  615,  616,
      626,  615,  612,  634,  953,  635,  637, 1005,  952,  634,
      939,  944,  941,  642,  638,  637,  648,  644, 1005,  652,
      940,  645,  656,  664, 1005, 1005,  664, 1005,  656,  663,
      649, 1005,  655,  656,  659,  662,  676,  665,  688,  687,
      683,  679, 1005,  694,  691,  703,  699,  694,  700,  697,

      698,  938,  937,  713,  715,  710,  705,  934,  700,  702,
      933,  708, 1005,  722,  723, 1005, 1005,  714,  726,  722,
      727,  736,  727,  745,  749,  735,  738,  738,  741,  746,
      744,  755,  748,  893,  785,  753,  723,  767,  750,  701,
      766,  764,  639,  771,  641,  777,  761,  769,  766,  774,
      786,  776,  772,  778,  797,  785, 1005, 1005,  797,  792,
      802,  790,  795,  798,  808,  795,  797,  814,  817,  808,
      806,  445,  814,  412, 1005,  807,  810,  823, 1005,  833,
      828, 1005,  817,  827,  402,  838,  347,  826,  835,  841,
      331,  852,  838,  837,  842,  838,  849,  850,  857,  857,

      856,  180,  856,  851,  864,  871, 1005,  149,  864,  143,
      878, 1005,  884,  867,  874,  881, 1005,  874,  878,  886,
      892, 1005,  890,  890,  885,   97, 1005, 1005, 1005,  900,
      887,  896,  895,   85, 1005,  894,  900, 1005, 1005,  960,
      963,   80,  966
    } ;

static const flex_int16_t yy_def[544] =
    {   0,
      539,    1,  539,  539,  539,  539,  539,  540,  541,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  539,  539,  539,  539,  540,  539,  540,  541,
      543,  539,  539,  539,  539,  539,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  543,  539,  542,  542,  542,  542,

      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  539,  542,  539,  539,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  539,  542,
      542,  542,  539,  542,  542,  539,  542,  539,  539,  542,
      542,  542,  542,  542,  542,  542,  542,  542,  542,  542,
      542,  539,  542,  539,  542,  542,  542,  542,  542,  542,
      542,  542,  542,  542,  542,  539,  542,  539,  539,  542,
      539,  542,  539,  539,  542,  542,  542,  542,  542,  542,

      539,  542,  542,  539,  539,  539,  539,  542,  539,  539,
      542,  539,  542,  542,  539,  542,  542,  542,  539,  539,
      539,  539,  542,  539,  542,  539,  539,  542,  542,  539,
      542,  542,  542,  539,  539,  539,  539,  542,  539,  539,
      539,  539,  542,  542,  539,  542,  542,  539,  539,  539,
      539,  539,  539,  542,  539,  539,  542,  542,  539,  542,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  542,  539,  542,  542,  539,  539,  539,  539,  539,
      539,  539,  542,  539,  539,  542,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  542,

      539,  542,  539,  539,  539,  539,  539,  542,  542,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,

      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,

      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,    0,  539,
      539,  539,  539
    } ;

static const flex_int16_t yy_nxt[1078] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   30,
       30,   32,   33,   34,   35,   36,   30,   37,   38,   39,
       40,   30,   41,   30,   42,    4,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   30,   32,   33,   34,   35,
       36,   30,   37,   38,   39,   40,   30,   41,   30,   42,
       43,   44,   45,   48,   45,   52,   58,   53,   59,   60,
       63,   71,   57,   65,   64,   45,   76,   45,  536,   77,
       61,   66,   73,   62,   78,   72,   81,   74,   75,   67,

      531,   58,   94,   68,   59,   60,   63,   71,   65,   69,
       64,   76,   70,   49,   77,   61,   66,   73,   62,   78,
       72,   81,   74,   75,   79,   67,   80,   82,   94,   68,
       84,   83,   48,   85,   69,   87,   97,   70,   88,   52,
       90,   53,   86,  101,  105,   89,  518,   91,  102,   79,
      111,   80,  516,   82,   92,   93,   84,   83,   85,   98,
      106,   87,   97,   99,   88,   90,  108,   86,  101,  105,
       89,  103,   49,   91,  102,  111,  100,  107,  104,  109,
       92,   93,  110,  511,  112,   98,  106,  113,  114,   99,
      116,  120,  108,  119,  121,  122,  103,  123,  124,  125,

      127,  100,  107,  104,  128,  109,  131,  132,  110,  112,
      129,  135,  113,  133,  114,  134,  116,  120,  119,  121,
      126,  122,  123,  124,  130,  125,  127,  136,  137,  138,
      128,  131,  139,  132,  140,  141,  129,  135,  133,  143,
      134,  144,  145,  146,  142,  126,  147,  148,  151,  130,
      150,  152,  136,  137,  154,  138,  155,  156,  139,  140,
      157,  141,  158,  159,  143,  160,  144,  145,  146,  142,
      161,  147,  162,  148,  151,  150,  163,  152,  164,  154,
      165,  155,  156,  166,  167,  157,  170,  158,  159,  168,
      160,  169,  171,  173,  175,  176,  161,  162,  177,  178,

      179,  182,  163,  180,  164,  181,  165,  183,  166,  167,
      184,  170,  185,  189,  168,  186,  169,  171,  173,  175,
      187,  176,  190,  177,  178,  191,  179,  182,  180,  192,
      181,  193,  183,  194,  500,  195,  184,  196,  185,  189,
      186,  197,  198,  199,  200,  187,  202,  203,  190,  208,
      496,  191,  211,  213,  205,  192,  206,  193,  209,  194,
      195,  214,  196,  216,  217,  219,  197,  198,  199,  218,
      200,  202,  203,  221,  207,  208,  210,  222,  211,  213,
      205,  223,  206,  224,  209,  225,  214,  226,  227,  216,
      217,  219,  228,  229,  218,  230,  231,  234,  221,  207,

      233,  210,  235,  222,  236,  494,  237,  223,  224,  239,
      232,  225,  226,  227,  238,  486,  240,  228,  229,  242,
      230,  243,  231,  234,  244,  233,  245,  250,  235,  246,
      236,  237,  247,  249,  239,  232,  251,  252,  253,  255,
      238,  240,  254,  256,  257,  242,  243,  258,  484,  259,
      244,  260,  245,  250,  246,  261,  262,  247,  249,  263,
      264,  265,  251,  252,  253,  255,  266,  254,  271,  256,
      257,  272,  273,  258,  259,  274,  275,  260,  278,  279,
      261,  267,  262,  268,  280,  263,  264,  265,  269,  284,
      270,  276,  266,  271,  277,  281,  272,  273,  283,  294,

      274,  285,  275,  286,  278,  279,  288,  267,  290,  268,
      280,  291,  292,  269,  284,  270,  276,  293,  295,  277,
      296,  281,  297,  298,  283,  294,  285,  299,  286,  300,
      301,  288,  302,  290,  303,  304,  291,  292,  306,  308,
      309,  320,  293,  310,  295,  296,  311,  297,  312,  298,
      313,  314,  299,  315,  317,  300,  301,  318,  302,  303,
      319,  304,  321,  306,  322,  308,  309,  320,  310,  324,
      326,  311,  327,  312,  329,  313,  314,  333,  315,  317,
      334,  337,  318,  335,  336,  319,  330,  321,  338,  322,
      339,  340,  341,  342,  345,  324,  326,  327,  343,  346,

      329,  347,  349,  333,  348,  350,  334,  337,  335,  336,
      351,  330,  352,  338,  353,  354,  339,  340,  341,  342,
      345,  355,  361,  343,  356,  346,  357,  347,  349,  348,
      358,  350,  359,  360,  362,  366,  351,  352,  363,  364,
      353,  354,  367,  368,  459,  369,  371,  355,  361,  356,
      372,  357,  373,  457,  374,  358,  375,  359,  360,  376,
      362,  366,  378,  363,  364,  379,  385,  367,  381,  368,
      369,  371,  386,  388,  389,  372,  390,  387,  373,  374,
      391,  375,  393,  394,  395,  376,  396,  398,  378,  397,
      399,  379,  385,  381,  400,  401,  402,  386,  388,  403,

      389,  390,  387,  404,  454,  405,  391,  393,  406,  394,
      395,  407,  396,  398,  397,  399,  408,  409,  410,  400,
      401,  402,  411,  412,  403,  413,  451,  414,  415,  404,
      405,  416,  417,  420,  406,  421,  422,  407,  423,  425,
      426,  408,  409,  428,  410,  429,  430,  411,  431,  412,
      433,  413,  414,  432,  415,  434,  416,  417,  435,  420,
      436,  421,  422,  423,  425,  426,  437,  438,  428,  439,
      444,  429,  430,  431,  440,  441,  433,  442,  432,  443,
      434,  445,  446,  435,  447,  450,  436,  452,  449,  453,
      455,  437,  456,  438,  458,  439,  444,  460,  464,  440,

      441,  461,  442,  462,  443,  463,  445,  465,  446,  447,
      450,  466,  467,  452,  453,  468,  455,  469,  456,  470,
      458,  471,  473,  460,  464,  472,  461,  474,  462,  475,
      463,  476,  477,  465,  478,  479,  466,  467,  480,  481,
      468,  482,  483,  469,  470,  485,  487,  471,  473,  488,
      472,  489,  474,  490,  475,  491,  476,  492,  477,  478,
      479,  493,  495,  499,  480,  481,  482,  483,  497,  498,
      485,  487,  501,  506,  488,  502,  503,  489,  504,  490,
      505,  491,  492,  507,  508,  509,  493,  510,  495,  499,
      512,  513,  514,  497,  498,  515,  448,  517,  501,  506,

      502,  503,  519,  504,  520,  505,  521,  522,  507,  523,
      508,  509,  510,  524,  525,  512,  513,  526,  514,  527,
      532,  515,  517,  528,  529,  530,  533,  534,  519,  535,
      520,  521,  522,  537,  538,  523,  427,  424,  524,  525,
      419,  418,  526,  392,  384,  527,  532,  383,  528,  529,
      530,  533,  534,  382,  535,  380,  377,  370,  537,  538,
       47,   47,   47,   50,  365,   50,   95,  344,   95,  332,
      331,  328,  325,  323,  316,  307,  305,  289,  287,  282,
      248,  241,  220,  215,  212,  204,  201,  188,  174,  172,
      153,  149,   96,  118,  117,  115,   96,  539,   56,   55,

       54,   51,   46,  539,    3,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539
    } ;

static const flex_int16_t yy_chk[1078] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    8,    5,   19,   23,   19,   24,   25,
       26,   29,  542,   27,   26,   45,   32,   45,  534,   33,
       25,   27,   31,   25,   34,   29,   36,   31,   31,   28,

      526,   23,   42,   28,   24,   25,   26,   29,   27,   28,
       26,   32,   28,    8,   33,   25,   27,   31,   25,   34,
       29,   36,   31,   31,   35,   28,   35,   37,   42,   28,
       38,   37,   47,   38,   28,   39,   58,   28,   39,   53,
       40,   53,   38,   60,   63,   39,  510,   41,   61,   35,
       68,   35,  508,   37,   41,   41,   38,   37,   38,   59,
       64,   39,   58,   59,   39,   40,   65,   38,   60,   63,
       39,   62,   47,   41,   61,   68,   59,   64,   62,   66,
       41,   41,   67,  502,   69,   59,   64,   70,   71,   59,
       73,   77,   65,   76,   78,   80,   62,   81,   82,   83,

       84,   59,   64,   62,   85,   66,   87,   88,   67,   69,
       86,   92,   70,   90,   71,   91,   73,   77,   76,   78,
       83,   80,   81,   82,   86,   83,   84,   93,   94,   98,
       85,   87,   99,   88,  100,  101,   86,   92,   90,  102,
       91,  103,  104,  105,  101,   83,  106,  107,  110,   86,
      109,  111,   93,   94,  113,   98,  114,  115,   99,  100,
      116,  101,  117,  118,  102,  119,  103,  104,  105,  101,
      122,  106,  123,  107,  110,  109,  124,  111,  125,  113,
      126,  114,  115,  127,  128,  116,  130,  117,  118,  129,
      119,  129,  131,  133,  135,  136,  122,  123,  138,  139,

      140,  144,  124,  141,  125,  143,  126,  145,  127,  128,
      147,  130,  148,  153,  129,  149,  129,  131,  133,  135,
      150,  136,  155,  138,  139,  156,  140,  144,  141,  157,
      143,  158,  145,  159,  491,  161,  147,  162,  148,  153,
      149,  163,  164,  165,  166,  150,  168,  169,  155,  173,
      487,  156,  177,  179,  172,  157,  172,  158,  174,  159,
      161,  180,  162,  182,  184,  186,  163,  164,  165,  185,
      166,  168,  169,  188,  172,  173,  174,  189,  177,  179,
      172,  190,  172,  191,  174,  192,  180,  193,  194,  182,
      184,  186,  195,  199,  185,  201,  202,  204,  188,  172,

      203,  174,  205,  189,  206,  485,  207,  190,  191,  209,
      202,  192,  193,  194,  208,  474,  210,  195,  199,  212,
      201,  213,  202,  204,  214,  203,  215,  220,  205,  216,
      206,  207,  217,  219,  209,  202,  221,  222,  224,  226,
      208,  210,  225,  227,  228,  212,  213,  229,  472,  230,
      214,  231,  215,  220,  216,  234,  235,  217,  219,  236,
      237,  239,  221,  222,  224,  226,  240,  225,  242,  227,
      228,  244,  245,  229,  230,  246,  247,  231,  249,  250,
      234,  241,  235,  241,  251,  236,  237,  239,  241,  255,
      241,  248,  240,  242,  248,  252,  244,  245,  254,  265,

      246,  256,  247,  257,  249,  250,  259,  241,  261,  241,
      251,  262,  263,  241,  255,  241,  248,  264,  266,  248,
      267,  252,  268,  269,  254,  265,  256,  270,  257,  272,
      273,  259,  275,  261,  276,  277,  262,  263,  279,  283,
      286,  297,  264,  287,  266,  267,  288,  268,  289,  269,
      290,  291,  270,  292,  294,  272,  273,  295,  275,  276,
      296,  277,  298,  279,  299,  283,  286,  297,  287,  301,
      303,  288,  304,  289,  307,  290,  291,  310,  292,  294,
      312,  315,  295,  313,  314,  296,  307,  298,  316,  299,
      317,  318,  319,  320,  323,  301,  303,  304,  321,  324,

      307,  325,  327,  310,  326,  328,  312,  315,  313,  314,
      329,  307,  330,  316,  331,  332,  317,  318,  319,  320,
      323,  333,  339,  321,  334,  324,  335,  325,  327,  326,
      336,  328,  337,  338,  340,  344,  329,  330,  341,  342,
      331,  332,  345,  346,  445,  347,  349,  333,  339,  334,
      350,  335,  351,  443,  352,  336,  353,  337,  338,  354,
      340,  344,  356,  341,  342,  357,  364,  345,  360,  346,
      347,  349,  365,  366,  367,  350,  368,  365,  351,  352,
      370,  353,  372,  373,  374,  354,  377,  380,  356,  379,
      381,  357,  364,  360,  383,  384,  385,  365,  366,  386,

      367,  368,  365,  387,  440,  388,  370,  372,  389,  373,
      374,  390,  377,  380,  379,  381,  391,  392,  394,  383,
      384,  385,  395,  396,  386,  397,  437,  398,  399,  387,
      388,  400,  401,  404,  389,  405,  406,  390,  407,  409,
      410,  391,  392,  412,  394,  414,  415,  395,  418,  396,
      419,  397,  398,  418,  399,  420,  400,  401,  421,  404,
      422,  405,  406,  407,  409,  410,  423,  424,  412,  425,
      430,  414,  415,  418,  426,  427,  419,  428,  418,  429,
      420,  431,  432,  421,  433,  436,  422,  438,  435,  439,
      441,  423,  442,  424,  444,  425,  430,  446,  450,  426,

      427,  447,  428,  448,  429,  449,  431,  451,  432,  433,
      436,  452,  453,  438,  439,  454,  441,  455,  442,  456,
      444,  459,  461,  446,  450,  460,  447,  462,  448,  463,
      449,  464,  465,  451,  466,  467,  452,  453,  468,  469,
      454,  470,  471,  455,  456,  473,  476,  459,  461,  477,
      460,  478,  462,  480,  463,  481,  464,  483,  465,  466,
      467,  484,  486,  490,  468,  469,  470,  471,  488,  489,
      473,  476,  492,  497,  477,  493,  494,  478,  495,  480,
      496,  481,  483,  498,  499,  500,  484,  501,  486,  490,
      503,  504,  505,  488,  489,  506,  434,  509,  492,  497,

      493,  494,  511,  495,  513,  496,  514,  515,  498,  516,
      499,  500,  501,  518,  519,  503,  504,  520,  505,  521,
      530,  506,  509,  523,  524,  525,  531,  532,  511,  533,
      513,  514,  515,  536,  537,  516,  411,  408,  518,  519,
      403,  402,  520,  371,  363,  521,  530,  362,  523,  524,
      525,  531,  532,  361,  533,  359,  355,  348,  536,  537,
      540,  540,  540,  541,  343,  541,  543,  322,  543,  309,
      308,  306,  302,  300,  293,  280,  278,  260,  258,  253,
      218,  211,  187,  181,  178,  170,  167,  152,  134,  132,
      112,  108,   96,   75,   74,   72,   52,   49,   22,   21,

       20,   18,    7,    3,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539,  539,  539,  539,
      539,  539,  539,  539,  539,  539,  539
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[94] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "socialstory.l"
#line 5 "socialstory.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "socialstory_tokens.h"

int yylex(void);
extern FILE *yyin;

YYSTYPE yylval;

static char* ss_strdup(const char* s) {
    size_t n = strlen(s) + 1;
    char* r = (char*)malloc(n);
    if (!r) { fprintf(stderr, "Out of memory\n"); exit(1); }
    memcpy(r, s, n);
    return r;
}

#define STANDALONE_LEXER
static const char* token_name(int t);
int main(int argc, char** argv) {
    if (argc > 1) {
        FILE* f = fopen(argv[1], "r");
        if (!f) { perror("fopen"); return 1; }
        yyin = f;
    }
    int tok;
    while ((tok = yylex()) != 0) {
        switch (tok) {
            case T_INT_LIT:    printf("%-20s %d (line %d)\n", token_name(tok), yylval.ival,  yylineno); break;
            case T_FLOAT_LIT:  printf("%-20s %g (line %d)\n", token_name(tok), yylval.fval,  yylineno); break;
            case T_STRING_LIT: printf("%-20s \"%s\" (line %d)\n", token_name(tok), yylval.sval,yylineno); free(yylval.sval); break;
            case T_ID:         printf("%-20s %s (line %d)\n", token_name(tok), yylval.sval,  yylineno); free(yylval.sval); break;
            default:           printf("%-20s (line %d)\n", token_name(tok), yylineno); break;
        }
    }
    return 0;
}
#line 927 "lex.yy.c"
#line 928 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 54 "socialstory.l"


#line 1148 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 540 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1005 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 56 "socialstory.l"
{ return T_GO_LIVE; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 57 "socialstory.l"
{ return T_GO_LIVE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 58 "socialstory.l"
{ return T_END_LIVE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 59 "socialstory.l"
{ return T_END_LIVE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "socialstory.l"
{ return T_THE_ACCOUNT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "socialstory.l"
{ return T_WAS_CREATED; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "socialstory.l"
{ return T_WAS_CREATED; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "socialstory.l"
{ return T_STARTED_WITH; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 65 "socialstory.l"
{ return T_BEGAN_AT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 66 "socialstory.l"
{ return T_GAINED; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "socialstory.l"
{ return T_LOST; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "socialstory.l"
{ return T_INCREASED_BY; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "socialstory.l"
{ return T_DECREASED_BY; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "socialstory.l"
{ return T_READS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "socialstory.l"
{ return T_WAS_UPDATED_TO; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "socialstory.l"
{ return T_IS_VIRAL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "socialstory.l"
{ return T_CONTAINS; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "socialstory.l"
{ return T_POSTS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 75 "socialstory.l"
{ return T_FEED; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 76 "socialstory.l"
{ return T_TEXT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 77 "socialstory.l"
{ return T_STATUS; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "socialstory.l"
{ return T_COUNT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "socialstory.l"
{ return T_RATIO; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 81 "socialstory.l"
{ return T_WHEN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 82 "socialstory.l"
{ return T_OTHERWISE_IF; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 83 "socialstory.l"
{ return T_OTHERWISE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 84 "socialstory.l"
{ return T_BECAME_GE; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 85 "socialstory.l"
{ return T_BECAME_GE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 86 "socialstory.l"
{ return T_BECAME_LE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 87 "socialstory.l"
{ return T_BECAME_LE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 88 "socialstory.l"
{ return T_BECAME_GT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 89 "socialstory.l"
{ return T_BECAME_LT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 90 "socialstory.l"
{ return T_BECAME_EQ; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 91 "socialstory.l"
{ return T_BECAME_NE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 93 "socialstory.l"
{ return T_EVERY_DAY_FOR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 94 "socialstory.l"
{ return T_DAYS; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 95 "socialstory.l"
{ return T_FOR_EACH; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 96 "socialstory.l"
{ return T_FROM; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 97 "socialstory.l"
{ return T_TO; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 99 "socialstory.l"
{ return T_STOP_FOLLOWING; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 100 "socialstory.l"
{ return T_SKIP_POST; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 102 "socialstory.l"
{ return T_THE_CHANNEL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 103 "socialstory.l"
{ return T_STARTS; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 104 "socialstory.l"
{ return T_IT_TAKES; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 105 "socialstory.l"
{ return T_UPLOAD; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 106 "socialstory.l"
{ return T_THE_CHANNEL_ENDS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 107 "socialstory.l"
{ return T_THE_CHANNEL_ENDS; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 108 "socialstory.l"
{ return T_CALL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 109 "socialstory.l"
{ return T_WITH; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 111 "socialstory.l"
{ return T_SHARE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 112 "socialstory.l"
{ return T_THE_USER_PROVIDED; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "socialstory.l"
{ return T_DETECT_VIRAL; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 "socialstory.l"
{ return T_CALCULATE_ENGAGEMENT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "socialstory.l"
{ return T_FIND_HIGHEST_REACH; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "socialstory.l"
{ return T_FIND_TOTAL_REACH; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "socialstory.l"
{ return T_REVERSE_CAPTION; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "socialstory.l"
{ return T_DETECT_SPAM; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "socialstory.l"
{ return T_CLAMP_ENGAGEMENT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "socialstory.l"
{ return T_BETWEEN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 123 "socialstory.l"
{ return T_AND; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 124 "socialstory.l"
{ return T_OR; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 125 "socialstory.l"
{ return T_NOT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 128 "socialstory.l"
{ return T_LPAREN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 129 "socialstory.l"
{ return T_RPAREN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 130 "socialstory.l"
{ return T_LBRACE; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 131 "socialstory.l"
{ return T_RBRACE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 132 "socialstory.l"
{ return T_COMMA; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 133 "socialstory.l"
{ return T_DOT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 134 "socialstory.l"
{ return T_PERCENT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 135 "socialstory.l"
{ return T_ASSIGN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 137 "socialstory.l"
{ return T_EQ; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 138 "socialstory.l"
{ return T_NEQ; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 139 "socialstory.l"
{ return T_GTE; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 140 "socialstory.l"
{ return T_LTE; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 141 "socialstory.l"
{ return T_GT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 142 "socialstory.l"
{ return T_LT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 144 "socialstory.l"
{ return T_PLUS; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "socialstory.l"
{ return T_MINUS; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 146 "socialstory.l"
{ return T_TIMES; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 147 "socialstory.l"
{ return T_DIVIDE; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 148 "socialstory.l"
{ return T_MOD; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 151 "socialstory.l"
{ yylval.fval = atof(yytext); return T_FLOAT_LIT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 152 "socialstory.l"
{ yylval.ival = atoi(yytext); return T_INT_LIT; }
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 153 "socialstory.l"
{ 
                                 size_t len = yyleng;
                                 char* s = (char*)malloc(len - 1); 
                                 if (!s) { fprintf(stderr, "Out of memory\n"); exit(1); }
                                 memcpy(s, yytext + 1, len - 2);
                                 s[len - 2] = '\0';
                                 yylval.sval = s;
                                 return T_STRING_LIT;
                               }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 164 "socialstory.l"
{ yylval.bval = 1; return T_YES; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 165 "socialstory.l"
{ yylval.bval = 0; return T_NO; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 168 "socialstory.l"
{ yylval.sval = ss_strdup(yytext); return T_ID; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 171 "socialstory.l"
{ }
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 172 "socialstory.l"
{ }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 173 "socialstory.l"
{  }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 174 "socialstory.l"
{  }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 177 "socialstory.l"
{ fprintf(stderr, "Lexical error at line %d: unexpected '%s'\n", yylineno, yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 178 "socialstory.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1690 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 540 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 540 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 539);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 178 "socialstory.l"


#ifdef STANDALONE_LEXER
static const char* token_name(int t) {
    switch (t) {
        case T_GO_LIVE: return "GO_LIVE";
        case T_END_LIVE: return "END_LIVE";
        case T_THE_ACCOUNT: return "THE_ACCOUNT";
        case T_WAS_CREATED: return "WAS_CREATED";
        case T_STARTED_WITH: return "STARTED_WITH";
        case T_BEGAN_AT: return "BEGAN_AT";
        case T_GAINED: return "GAINED";
        case T_LOST: return "LOST";
        case T_INCREASED_BY: return "INCREASED_BY";
        case T_DECREASED_BY: return "DECREASED_BY";
        case T_READS: return "READS";
        case T_WAS_UPDATED_TO: return "WAS_UPDATED_TO";
        case T_IS_VIRAL: return "IS_VIRAL";
        case T_CONTAINS: return "CONTAINS";
        case T_POSTS: return "POSTS";
        case T_FEED: return "FEED";
        case T_TEXT: return "TEXT";
        case T_STATUS: return "STATUS";
        case T_COUNT: return "COUNT";
        case T_RATIO: return "RATIO";
        case T_YES: return "YES";
        case T_NO: return "NO";
        case T_WHEN: return "WHEN";
        case T_OTHERWISE_IF: return "OTHERWISE_IF";
        case T_OTHERWISE: return "OTHERWISE";
        case T_BECAME_GT: return "BECAME_GT";
        case T_BECAME_GE: return "BECAME_GE";
        case T_BECAME_LT: return "BECAME_LT";
        case T_BECAME_LE: return "BECAME_LE";
        case T_BECAME_EQ: return "BECAME_EQ";
        case T_BECAME_NE: return "BECAME_NE";
        case T_EVERY_DAY_FOR: return "EVERY_DAY_FOR";
        case T_DAYS: return "DAYS";
        case T_FOR_EACH: return "FOR_EACH";
        case T_FROM: return "FROM";
        case T_TO: return "TO";
        case T_STOP_FOLLOWING: return "STOP_FOLLOWING";
        case T_SKIP_POST: return "SKIP_POST";
        case T_THE_CHANNEL: return "THE_CHANNEL";
        case T_STARTS: return "STARTS";
        case T_IT_TAKES: return "IT_TAKES";
        case T_UPLOAD: return "UPLOAD";
        case T_THE_CHANNEL_ENDS: return "THE_CHANNEL_ENDS";
        case T_CALL: return "CALL";
        case T_WITH: return "WITH";
        case T_SHARE: return "SHARE";
        case T_THE_USER_PROVIDED: return "THE_USER_PROVIDED";
        case T_DETECT_VIRAL: return "DETECT_VIRAL";
        case T_CALCULATE_ENGAGEMENT: return "CALCULATE_ENGAGEMENT";
        case T_FIND_HIGHEST_REACH: return "FIND_HIGHEST_REACH";
        case T_FIND_TOTAL_REACH: return "FIND_TOTAL_REACH";
        case T_REVERSE_CAPTION: return "REVERSE_CAPTION";
        case T_DETECT_SPAM: return "DETECT_SPAM";
        case T_CLAMP_ENGAGEMENT: return "CLAMP_ENGAGEMENT";
        case T_BETWEEN: return "BETWEEN";
        case T_AND: return "AND";
        case T_OR: return "OR";
        case T_NOT: return "NOT";
        case T_LPAREN: return "LPAREN";
        case T_RPAREN: return "RPAREN";
        case T_LBRACE: return "LBRACE";
        case T_RBRACE: return "RBRACE";
        case T_COMMA: return "COMMA";
        case T_DOT: return "DOT";
        case T_PERCENT: return "PERCENT";
        case T_ASSIGN: return "ASSIGN";
        case T_PLUS: return "PLUS";
        case T_MINUS: return "MINUS";
        case T_TIMES: return "TIMES";
        case T_DIVIDE: return "DIVIDE";
        case T_MOD: return "MOD";
        case T_EQ: return "EQ";
        case T_NEQ: return "NEQ";
        case T_GT: return "GT";
        case T_LT: return "LT";
        case T_GTE: return "GTE";
        case T_LTE: return "LTE";
        case T_ID: return "ID";
        case T_INT_LIT: return "INT_LIT";
        case T_FLOAT_LIT: return "FLOAT_LIT";
        case T_STRING_LIT: return "STRING_LIT";
        default: return "UNKNOWN";
    }
}
#endif

#ifdef _WIN32
#include <windows.h>

int WINAPI WinMain(HINSTANCE hInst, HINSTANCE hPrev, LPSTR lpCmdLine, int nShowCmd) {
    return main(__argc, __argv);
}
#endif

